-- 123_event_flood_cleanup.sql
--
-- Production measurement, 30 days, `lead_events` by type:
--
--   sla_breach                 2219 rows across    3 leads
--   state_transition_rejected  1257 rows across    8 leads
--   manual_return_to_ai         939 rows across    6 leads
--   ...
--   inbound_message_received      34 rows
--   human_reply_sent               6 rows
--
-- Over 90% of the table is machine noise generated by about ten leads, and
-- every row of it mirrors into `activities` (migration 054). `lead-detail`
-- returns the newest 400 activities, so on those leads the real conversation
-- was pushed out of the window entirely and the chat pane rendered "עוד אין
-- הודעות בשיחה" over a full WhatsApp history. The worst-affected lead holds
-- 1176 events; the one the owner reported holds 581.
--
-- The emitters are fixed in code (sla-worker gates on the queue item being
-- new). This migration deals with the two the emitters cannot fix, and with
-- the backlog already in the table.

-- ── 1. Stop re-logging identical rejected transitions ────────────────
-- A rejected transition changes nothing, so logging the same
-- (lead, from, to) again an hour later adds no information — it just
-- buries the lead's history. Statuses like active_student and duplicate
-- have NO legal targets at all, so every attempt against them is rejected
-- forever, which is how 8 leads produced 1257 rows.
create or replace function public.transition_lead_status(
  p_lead_id uuid,
  p_target text,
  p_actor_type text default 'system',
  p_reason text default null
) returns leads
language plpgsql security definer set search_path = public as $$
declare
  v_current text;
  v_legal text[] := array[]::text[];
  v_lead leads;
begin
  select lead_status into v_current from leads where id = p_lead_id for update;
  if v_current is null then
    return null;
  end if;

  v_legal := case v_current
    when 'new' then array['first_contact_sent','manual_review_required','do_not_contact','removed_by_request']
    when 'first_contact_sent' then array['responded','nurture','human_handoff','lost','do_not_contact','removed_by_request']
    when 'responded' then array['qualified','nurture','checkout_pushed','human_handoff','lost','do_not_contact','removed_by_request']
    when 'qualified' then array['checkout_pushed','human_handoff','nurture','lost','do_not_contact','removed_by_request']
    when 'nurture' then array['responded','qualified','dormant','lost','do_not_contact','removed_by_request']
    when 'checkout_pushed' then array['payment_pending','won','human_handoff','lost','do_not_contact','removed_by_request']
    when 'payment_pending' then array['won','human_handoff','lost','do_not_contact','removed_by_request']
    when 'human_handoff' then array['responded','qualified','checkout_pushed','payment_pending','won','nurture','lost','do_not_contact','removed_by_request']
    when 'won' then array['onboarding_active','active_student']
    when 'lost' then array['nurture','dormant']
    when 'dormant' then array['responded','nurture','lost']
    when 'onboarding_active' then array['active_student']
    when 'manual_review_required' then array['first_contact_sent','human_handoff','lost','do_not_contact']
    else array[]::text[]
  end;

  if p_target = v_current then
    select * into v_lead from leads where id = p_lead_id;
    return v_lead;
  end if;

  if not p_target = any(v_legal) then
    -- Log the first rejection of this exact (from, to) pair, then stay
    -- quiet about it for a day. A rejected transition changes nothing, so
    -- re-logging it every ten minutes adds no information — it just buries
    -- the lead's real history. Statuses such as active_student and
    -- duplicate have NO legal targets at all, so every attempt against them
    -- is rejected forever: that is how 8 leads produced 1257 rows in a
    -- month. The caller still gets NULL either way; only the audit volume
    -- changes.
    if not exists (
      select 1 from lead_events
      where lead_id = p_lead_id
        and event_type = 'state_transition_rejected'
        and created_at > now() - interval '24 hours'
        and event_payload->>'from' = v_current
        and event_payload->>'to' = p_target
    ) then
      insert into lead_events(lead_id, event_type, actor_type, event_payload)
      values (p_lead_id, 'state_transition_rejected', p_actor_type,
              jsonb_build_object('from', v_current, 'to', p_target, 'reason', p_reason));
    end if;
    return null;
  end if;

  update leads set lead_status = p_target, updated_at = now() where id = p_lead_id
    returning * into v_lead;

  insert into lead_events(lead_id, event_type, actor_type, event_payload)
  values (p_lead_id, 'lead_status_changed', p_actor_type,
          jsonb_build_object('from', v_current, 'to', p_target, 'reason', p_reason));

  return v_lead;
end;
$$;
revoke all on function public.transition_lead_status(uuid,text,text,text) from public;
grant execute on function public.transition_lead_status(uuid,text,text,text) to service_role;

-- ── 2. Clear the backlog ─────────────────────────────────────────────
-- Deletes only the three machine-noise types, only rows older than 24
-- hours, and keeps the 5 most recent of each type per lead so the history
-- still shows that the condition occurred and when it last did. Nothing a
-- human did, and no message, is touched.
--
-- Batched at 5000 to keep each statement's lock short — these tables carry
-- an AFTER trigger that writes to `activities`, so the delete cascades
-- there and a single unbounded statement would hold locks far too long.
do $$
declare
  v_deleted integer;
  v_total integer := 0;
  v_before integer;
begin
  select count(*) into v_before from lead_events;

  loop
    with ranked as (
      select id,
             row_number() over (
               partition by lead_id, event_type order by created_at desc
             ) as rn
      from lead_events
      where event_type in ('sla_breach', 'state_transition_rejected', 'manual_return_to_ai')
        and created_at < now() - interval '24 hours'
    ),
    doomed as (
      select id from ranked where rn > 5 limit 5000
    )
    delete from lead_events e using doomed d where e.id = d.id;

    get diagnostics v_deleted = row_count;
    v_total := v_total + v_deleted;
    exit when v_deleted = 0;
  end loop;

  raise notice 'lead_events flood cleanup: % rows before, % deleted, % remaining',
    v_before, v_total, v_before - v_total;
end $$;

-- The mirror rows are deleted by the lead_events cascade only if one is
-- defined; migration 054's trigger is INSERT-side, so orphaned activity
-- rows are cleaned up here explicitly by the same rule.
do $$
declare
  v_deleted integer;
  v_total integer := 0;
begin
  loop
    with doomed as (
      select a.id
      from activities a
      where a.source_table = 'lead_events'
        and a.title in ('sla_breach', 'state_transition_rejected', 'manual_return_to_ai')
        and a.occurred_at < now() - interval '24 hours'
        and not exists (select 1 from lead_events e where e.id = a.source_id)
      limit 5000
    )
    delete from activities a using doomed d where a.id = d.id;

    get diagnostics v_deleted = row_count;
    v_total := v_total + v_deleted;
    exit when v_deleted = 0;
  end loop;

  raise notice 'activities mirror cleanup: % rows deleted', v_total;
end $$;
